server:
  port: 5599
spring:
  boot:
    admin:
      client:
        # 如果存在load balance 则可以使用lb
        url: http://127.0.0.1:7777
        username: livk
        password: 123456
        instance:
          service-host-type: ip
          metadata:
            user:
              name: ${spring.boot.admin.client.username}
              password: ${spring.boot.admin.client.password}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
