spring:
  profiles:
    active: dev
  freemarker:
    template-loader-path: classpath:/templates/ftl/
  mail:
    host: smtp.qq.com
    username: xxxxxx@qq.com
    password: xxxxxx
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true

