spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://livk.com:3306/batch_config
    username: root
    password: 123456
  sql:
    init:
      schema-locations: classpath:data.sql
      mode: always
server:
  port: 6688
mybatis:
  mapper-locations: classpath:/mapper/**.xml
