spring:
  batch:
    jdbc:
      initialize-schema: always
      table-prefix: BATCH_
    job:
      enabled: false
      name: parentjob
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://livk.com:3306/batch_config
    username: root
    password: 123456
#  sql:
#    init:
#      schema-locations: classpath*:/org/springframework/batch/core/schema-mysql.sql
#      platform: mysql
#      mode: always
