server:
  port: 7777

spring:
  thymeleaf:
    check-template-location: false
  boot:
    admin:
      instance-auth:
        default-user-name: ${spring.security.user.name}
        default-password: ${spring.security.user.password}
  security:
    user:
      name: livk
      password: 123456

  data:
    redis:
      host: ${REDIS_HOST:livk.com}
      password: 123456

management:
  endpoints:
    web:
      exposure:
        include: '*'
